In [10]:
z = "'I am learning Python, \n specifically for data analysis'" # A very basic string

a = "5" # The number "5" as a string

a = '5' # Single quotations to create a string

a_two = "'5'" # Surround one type of quotation with another one to make that quotation part of the string

b = """This is a 
multiline string""" # Triple quotes to denote a multiline string

c = "Escaping a character \''" # Use a "\" to "escape a character" meaning that you'll print that character as is. This is useful for when you need to use special characters like single quotes

d = "this is how you create a \n newline, which is kind of like hitting the enter key" # Use "\n" to denote a newline

print(z) # Use the "print" function to look at all of these outputs
print(a)
print(a_two)
print(b)
print(c)
print(d)
print(z[3:14])

x =7.7
y = 7.8
print(type(y))
print(y + x)
print(y),x
print(z[0])
print(z[:7])

a == z

'I am learning Python, 
 specifically for data analysis'
5
'5'
This is a 
multiline string
Escaping a character ''
this is how you create a 
 newline, which is kind of like hitting the enter key
am learning
<class 'float'>
15.5
7.8
'
'I am l


False

In [26]:
m_list = [9, 8, 7, 'me', 'you', 6]
q_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

print(m_list[:]) # : this prints everything in the list
print(m_list[::-1]) # ::-1 this prints backswards and zero is invalid in this way
print(q_list[::2]) # ::2 this prints every second number from the first which is zero(You can give it any int)
print(q_list[1::2]) # 1::2 You can assign where you want it to start from and how it should count when printing out

[9, 8, 7, 'me', 'you', 6]
[6, 'you', 'me', 7, 8, 9]
[1, 3, 5, 7, 9]
[2, 4, 6, 8]


# **Data types**

 # : this prints everything in the list
 # ::-1 this prints backswards and zero is invalid in this way
 # ::2 this prints every second number from the first which is zero(You can give it any int)
 # 1::2 You can assign where you want it to start from and how it should count when printing out

# **Dictionary**

In [27]:
dictionary = {'Matt':"Gift", 'judy':"Love"}
dictionary.get('judy')

'Love'

# These work like the actual dic, you assign one **string** a **value(key)** by using '' or ""

# And you can print then out by calling out that dic's name and add **.get**
* get

In [30]:
multi = 'matt ' * 4
multi

'matt matt matt matt '

# You can multiply a string like, how many times
# do you want it to be print
# but you can not add, because adding in python its like concatenating 

### modulo = 10%3 # Gives you the the remainder of a division operation

### floor_division = 7 // 2 # Gives you the largest multiple, in this case it's 3 

In [32]:
print(3 == 3) # Equals

print(3 != 4)  # Does not equal

print(3 > 4)  # Greater than

print(3 < 5)  # Less than

print(2 >= 2)  # Greater than or equal to

print(4 <= 4)  # Less than or equal to

True
True
False
True
True
True


In [33]:
int(5.6)

5

In [34]:
'ba' in 'adidas'

False

In [35]:
'u' in 'you'

True

# **Functions**

In [ ]:
def function_name(x, y, z):
	return x + y + z # The "return" tells Python what to output from a function

function_name(x = 1, y = 2, z = 3) # This is how we call a function
function_name(1, 2, 3) # You can also call it like this by letting Python assume your arguments are in order 
function_name(1, 2, z = 4) # You can also not specify earlier arguments, but specify later ones
function_name(x = 1, 2, 3) # This is not valid (Python doesn't know what arguments to match 2 and 3 with

In [39]:
def function_name(x, y, z):
	return x + y + z # The "return" tells Python what to output from a function

function_name(x = 1, y = 2, z = 3) # This is how we call a function


6

# **Numpy**
## The order of them is:
* How to import
* How to call and use it
* And some arrays

In [1]:
import numpy

In [1]:
test = [1, 2, 3, 4]

test.append(3)

In [4]:
import numpy as np

e = np.array([1, 2, 3, 4, 5, 6])
print(e.sum()) # Sum the array
print(e.min()) # Find the minimum value in an array
print(e.max()) # Find the maximum value in an array
print(e.mean()) # Find the arithmetic mean of an array

c = np.array([2, 3, 4, 5, 6, 2]).reshape(2, 3) #the reshape tells it how many raws(first number) and raws(sec number)
d = np.array([2, 3, 4, 5, 6, 2, 3, 5]).reshape(2, 2, 2)
print(c)
print(d)

21
1
6
3.5
[[2 3 4]
 [5 6 2]]
[[[2 3]
  [4 5]]

 [[6 2]
  [3 5]]]


In [6]:
import numpy as np 

a = np.zeros(5) # Creates an array of zeros with 5 elements
b = np.linspace(0, 6, 10) # Creates an array of values from 0 through 6 in 10 even spaces
c = np.random.rand(3) # Three random values between 0 and 1
d = np.random.randint(1, 1000) # A random integer between 1 and 1000
e = np.arange(25) # Like the "Range" function we learned earlier, this is gives you a range of integers between 1 - 25
print(a)
print(b)
print(c)
print(d)
print(e)

[0. 0. 0. 0. 0.]
[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]
[0.16186779 0.44505856 0.76107478]
461
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


# **Pandas**
## To install:
* In Anaconda Prompt enter *conda install pandas* Type y and hit "Enter" and Conda should start installing the package.

## To use:
* import pandas as pd

In [1]:
import pandas as pd

series_test = [1, 2, 3, 6, 7]
print(pd.Series(series_test))
# You'll see the output is "two" columns. The index on the left and the data on the right. 
# The index is "kind-of" a column, but is better understood as the "address" of data in Pandas. 
# We'll be working a lot with indices in the future. 

0    1
1    2
2    3
3    6
4    7
dtype: int64


In [ ]:
import os # This will be used to tell us where the file is
import pandas as pd

pwd = os.getcwd() # This creates a string of the folder this Python Script is stored in

filepath = pwd + "/simple_csv.csv" # This creates a string that is the filepath to the simple_csv file

first_import = pd.read_csv(filepath) # This reads the csv into Python
first_import